# .github/workflows/publish-release.yml
name: Publish release
on:
  workflow_dispatch:
  push:
    branches:
      - 'release/v*.*.*'

jobs:
  check-permission:
    name: check permission
    runs-on: ubuntu-latest
    steps:
      - id: check
        uses: shogo82148/actions-check-permissions@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    needs:
      - check-permission
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git for GitHub Actions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract version from branch name
        id: extract_version
        run: |
          # Extract version from the branch name (e.g., release/v1.2.3 -> 1.2.3)
          version="${GITHUB_REF#refs/heads/release/v}"
          echo "Extracted version: $version"
          echo "::set-output name=version::$version"

      - name: Pull the latest changes from the remote branch
        run: |
          git pull origin ${{ github.ref_name }}

      - name: Bump version and commit
        id: bump_version
        run: |
          set +e
          # Extract the version from the tag name (e.g., refs/tags/v1.2.3 -> 1.2.3)
          version=${{ steps.extract_version.outputs.version }}
          echo "Current version is $version"
          # Create a VERSION file to track the version
          echo $version > VERSION
          git add VERSION
          git commit -m "chore: bump version to $version"
          git push origin HEAD

      - name: Create Tag
        run: |
          set +e
          version=${{ steps.extract_version.outputs.version }}
          git tag "v$version"
          git push origin "v$version"

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff-changelog
        with:
          config: cliff.toml
          args: --strip header
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit CHANGELOG.md update
        run: |
          set +e
          git add CHANGELOG.md
          git commit -m "docs: Update CHANGELOG for version ${{ steps.extract_version.outputs.version }}"
          git branch -m main
          git push origin HEAD

      - name: Generate a release note
        uses: orhun/git-cliff-action@v3
        id: git-cliff-release
        with:
          config: cliff.toml
          args: --latest --strip header
        env:
          OUTPUT: RELEASE.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE.md
          tag_name: "v${{ steps.extract_version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up RELEASE.md
        run: |
          rm RELEASE.md
